export async function builderEngine(data) {
  const trends = data.market || [];

  const generated = trends.slice(0, 5).map((t, i) => ({
    id: `ai-product-${Date.now()}-${i}`,
    title: `AI Generated ${t.category || "Product"} ${i}`,
    price: Math.floor(Math.random() * 80) + 20,
    views: 0,
    clicks: 0,
    orders: 0,
    autoGenerated: true,
  }));

  console.log("🏗️ PRODUCTS CREATED:", generated.length);

  return generated;
}
