import { db } from "../config/firebase";
import { doc, setDoc } from "firebase/firestore";

/* ================= BUILDER ENGINE ================= */
export async function builderEngine(decisions) {
  for (const item of decisions.slice(0, 3)) {
    const id = `ai-${Date.now()}-${Math.random()}`;

    await setDoc(doc(db, "products", id), {
      id,
      title: `AI Generated: ${item.title || "Product"}`,
      price: item.price || 19,
      views: 0,
      clicks: 0,
      orders: 0,
      viralBoost: true,
      autoGenerated: true,
      createdAt: Date.now(),
    });

    console.log("🧱 CREATED PRODUCT:", id);
  }
}
